### PR TITLE
Build with Julia 1.11, DPPL 0.31, Turing 0.35.3

### LINKED ISSUE #560: Path to Julia 1.11
- [x] Update Manifest, make sure to run with Julia 1.11
   - [x] Dependency resolution failed offline because Pathfinder.jl doesn't yet have a version compatible with Turing 0.35. I bumped the compat entry on a local clone of Pathfinder, which allowed dependencies to be successfully resolved (which implies that there aren't any other packages that also have conflicting dependency resolution). I opened https://github.com/mlcolab/Pathfinder.jl/pull/214; when this is merged and released we can update the deps.
   - [x] Precompilation failed. https://github.com/TuringLang/Bijectors.jl/pull/337 should fix it. Get this merged and released.
       - [x] Bump Bijectors compat on Turing https://github.com/TuringLang/Turing.jl/pull/2384
           - [x] Bump Bijectors compat on AdvancedVI https://github.com/TuringLang/AdvancedVI.jl/pull/136
           - [x] Bump Bijectors compat on DynamicPPL https://github.com/TuringLang/DynamicPPL.jl/pull/701
               - [x] Get DynamicPPL CI passing with Turing
       - [x] Make Bijectors compatible with Enzyme 0.13 https://github.com/TuringLang/Bijectors.jl/pull/350 This is necessary because AdvancedVI requires Enzyme 0.13.

### PR DESCRIPTION
**Pull request by penelopeysm**
Closes #560

Now that Bijectors is (indirectly) compatible with Enzyme 0.13, and corresponding compat entries in DynamicPPL and Turing have been updated to use that new version, the docs environment can now be resolved with Julia 1.11.

Specifically, it should let us use the latest version of Turing (0.35.3 at the time of writing). This should also give us back the green tick on the version check workflow.

- [x] To make this happen, there is one remaining package that needs a DPPL compatibility bump, namely TuringBenchmarking. I've triggered the release and this should go through soon.
- [x] Mooncake needs a DPPL bump too. https://github.com/compintell/Mooncake.jl/pull/404
- [x] Pathfinder now needs a DPPL bump: https://github.com/mlcolab/Pathfinder.jl/pull/220

### CODE REVIEW

**Comment by willtebbutt** [comment]
Apologies -- version 0.4.54 of Mooncake should be available in the next 20 mins or so, and ought to make this work correctly!

**Comment by penelopeysm** [comment]
> in the next 20 mins or so

Little did we know...
